import './globals.css';
import type { Metadata } from 'next';
import { Inconsolata } from 'next/font/google';
import clsx from 'clsx';

const inconsolata = Inconsolata({ subsets: ['latin'], display: 'auto' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={clsx(inconsolata.className, 'text-themeGray')}>{children}</body>
    </html>
  );
}
